### ISSUE TITLE
this.request.body doesn't return nothing anymore

### ISSUE THREAD

**Issue by iboxgithub** [iron-meteor/iron-router#1003]
Hi,

I had my API fully functional and everything was working like a charm but with the last updates of Iron Router (Meteor update could impact?) my command 

this.request.body 

doesn't render nothing when I have a POST call on my API (all calls work good and I have no problem with GET this.params), I took a look at the docs and I don't see nothing talking about this, does anyone have an idea?

Thanks for your help

**Comment by bitomule** [comment]
I've having the same problem. I've this code working:

    Router.onBeforeAction(Iron.Router.bodyParser.json());
Router.onBeforeAction(Iron.Router.bodyParser.urlencoded({extended: false}));
Router.onBeforeAction(Iron.Router.bodyParser.text());

Updated iron router and now post body is always empty. I've tried removing it and still doesn't work. How can I fix it?

**Comment by travisdahl** [comment]
Similar to @MiroRadenovic's screenshot. My nested attributes are no longer available via dot syntax.

I used to be able to access `@request.body.profile.first_name` but now its coming through as a single key instead of nested JSON `'profile[first_name]': 'trav'` so a majority of my code is broken. Is there a  solution for this?
