### ISSUE TITLE
How to prevent FOUC ("Flash of Unstyled Content") in a Meteor app

### ISSUE THREAD

**Issue by johanbrook** [iron-meteor/iron-router#1176]
Hi!

We're using the [fourseven:scss](https://github.com/fourseven/meteor-scss/) package to compile SCSS to CSS easily. But we've experienced some flashes of unstyled content in a Meteor app with Iron Router when navigating between routes. The markup would appear unstyled for a brief second, that is. There is nothing special about the setup: just a regular, semi-large app with a SCSS foundation. 

Is this an issue one can prevent somehow in Iron Router? Any similar cases? 

Thanks!

**Comment by TimFletcher** [comment]
Seems strange. Is this in production or development?

I'm using `fourseven:scss` and Iron Router but I don't get any FOUC. It can't be related to compilation because your app would have the old css before the new i.e. there's always CSS present. In production the CSS is always present as there's no page reloads when moving between routes.

Can you provide more information?

**Comment by johanbrook** [comment]
This is not an issue anymore, I tracked it down to be in another part of our app. Sorry, and thanks!

**Comment by TimFletcher** [comment]
Great. Thanks for closing!
