### ISSUE TITLE
% Isn't url decoded correctly

### ISSUE THREAD

**Issue by d0liver** [iron-meteor/iron-router#1254]
Specifically, if http://somewhere/path is a route then curl http://somewhere/path?q=%25 will cause this.params.query.q to be undefined instead of '%'.

**Comment by RodMagnuson** [comment]
I see this as well

**Comment by fongandrew** [comment]
Also running into this error. The percent symbol appears to be decoded twice. I've set up a simple repro on Meteorpad: http://meteorpad.com/pad/7ArsrxRXhhvux73tE/Iron:Router%20Query%20Param%20Test

If you submit the form in the Meteorpad with a value of `Bob%20Loblaw`, you get a querystring encoding of `Bob%2520Loblaw`. Expected behavior would be for Iron:Router to decode this back into `Bob%20Loblaw`. Instead, Iron:Router appears to process the string twice and returns `Bob Loblaw`.

**Comment by winstoncse** [comment]
+1

**Comment by leinaD-natipaC** [comment]
I have the same undefined problem. When my route has something like `"etc/?someParam=otilde%F3"` the entire params.query becomes undefined, breaking everything that ever uses the link's parameters. How is this issue a year old?

**Comment by saginadir** [comment]
+1

**A solution until this is fixed:**

use:
`this.request.query` - decoded once

Instead of:
`this.params.query` - decoded twice and returns undefined on encoded params

**Comment by chrisbutler** [comment]
@d0liver @RodMagnuson @fongandrew @winstoncse @leinaD-natipaC @saginadir fixed in 1.1.2
