### ISSUE TITLE
Iron Router 'Home' showing when deployed to Modulus

### ISSUE THREAD

**Issue by huntonas** [iron-meteor/iron-router#1289]
Locally, my 'home' template is loaded when the app starts up, but when I deployed the application to Modulus, the Iron Router 'Home' template is displayed. I tried creating a route on the server, but I got an error. I am sure I am missing something, but I am not sure what. Any ideas?

**Comment by huntonas** [comment]
I tried renaming the 'home' template to index, and I am still getting the Iron Router 'Home' template. My routes are all client side. Here they are:

    Router.route('/', {
	name: 'index',
	controller: 'IndexController'
    });
    Router.route('/about', {
	name: 'about',
	controller: 'AboutController'
    });
    Router.route('/art/:_id', {
	name: 'art',
	controller: 'ArtController'
    });
    Router.route('/admin', {
	name: 'admin',
	controller: 'AdminController'
    });

**Comment by gbaladi** [comment]
I have the same problem deploying with mup (meteorup)

**Comment by huntonas** [comment]
Well that is what I was setting up to try, but I will hold off for now.

**Comment by huntonas** [comment]
@gbaladi this fixed it for me http://stackoverflow.com/questions/27999019/iron-router-showing-splash-page-when-deployed-works-fine-on-local

**Comment by gbaladi** [comment]
thanks @huntonas. This don't work for me. The problem with my app is caused by 2 templates with the same name. I read this https://github.com/iron-meteor/iron-router/issues/1168#issuecomment-78245558 and notice the error. I can't explain why at localhost iron:router behaves different.

**Comment by speizerj** [comment]
For anyone who finds this, what worked for me was using "modulus deploy -D" to deploy my app in debug mode. So because that works for me I think that I have an issue with the minifying of my code (running in debug mode prevents the minifying, I believe). I need to investigate further but it's working for now and thought this might help someone.

**Comment by igoodrich** [comment]
Happening for me as well.  For me, it was _not_ the presence of npm.js, nor 2 templates of the same name.  The -D deploy helped it work for now.  Thanks @speizerj it did help someone... me!

I think _any_ (or a large number) of JS errors can interfere with the iron router initialization, thus causing the error that happens when iron router does not initialize properly. 

Good advice here:
http://stackoverflow.com/questions/27156922/iron-router-meteor-production-error

Run your app locally in production mode
    meteor --production

and then open JS console to look for errors errors.

**Comment by speizerj** [comment]
@igoodrich glad it helped. My issue seemed to resolve itself over the course of development (I cleaned up my external js files but never checked to see which one was the offender) but that's good advice to use meteor --production locally. Cheers

**Comment by dsjoerg** [comment]
+1 this problem is biting me as well.

**Comment by chrisbutler** [comment]
@dsjoerg this is likely an issue with your code, not an IR bug

**Comment by dsjoerg** [comment]
@chrisbutler it is both.  A problem in my code should not cause IR to show the 'Home' template.

**Comment by chrisbutler** [comment]
@dsjoerg if your code has issues that interfere with the router initialization/configuration, but the package loads properly... what else could iron router show? 

if there are previous JS errors in other areas, there's likely no way for the router to tell

a reproduction would be helpful here so we can see if there's anything else that can be done...

**Comment by dsjoerg** [comment]
@chrisbutler I had a simple client-side-only JS bug (I was calling _ensure() on a collection in client-side code).  In my development environment IR worked fine and had no complaints.  Only in production did things go wrong, and the only symptom was IR showing the home template.  The IR initialization code was getting called, I did a console.log immediately before to verify that.

If IR is unable to tell the difference between this case and a "no initialization" case, then another approach would be for IR's dev mode to be more like production behavior so that this class of problem can be more readily detected and dealt with.

**Comment by chrisbutler** [comment]
@dsjoerg this isn't a router issue, it's a JS/Meteor issue. see https://github.com/iron-meteor/iron-router/issues/1481#issuecomment-161048840 for more
