### ISSUE TITLE
waitOn in Router.configure in new version of iron:router seems not working

### ISSUE THREAD

**Issue by TimoRuetten** [iron-meteor/iron-router#1336]
I have a problem with the waitOn property when using it in Router.configure(). I do not find a reference tot his so I think this isnt a thing which does not change so I think its an error.

My Route.configure looks like this:

``` javascript
Route.configure({
 layoutTemplate : 'my_layout',
 waitOn : function () {
    return [Meteor.subscribe('categories')];
 }
});
```

This is because I need the categories collection on all my pages - because of this I want to subscribe it globally on every route. When I have this in my code it doesnt work.

This error appears in console:

Exception in callback of async function: Error: 
You called wait() after calling ready() inside the same computation tree.

In my example I am in the "media" route which looks exactly like this:

``` javascript
Router.route('/admin/media', function() {
    this.render('navigation_admin_media', {
        to : 'above_content_all'
    });

    this.subscribe('my_media').wait();

    if (this.ready()) {
        this.render('loremipsum');
    } else {
        this.render('loading');
    }

}, {
    name : 'admin_media',
    onBeforeAction : function () {
        Session.set('admin.medias.selected', []);
        this.next();
    }
});
```

I guess the problem is the this.subscribe() method but I dont know how else to do this - I dont want to be that the hole route is waiting for the subscribtion and instead I just want that one specific template (in this case its loremipsum) is waiting before the subscribtion is ready.

It works when I put my categorie subscribtion insider of my route but then I have to add this on every route ... I guess there is any global solution, right ? Before the new version of iron:router it was to define it in Router.configure.

**Comment by steveinatorx** [comment]
i thought i would respond to this old issue as i also ran into this problem with iron router - although i suspect that this is really a meteor idiosyncrasy. When you try to componentize anything really to use across individual route definitions the Router context gets lost so you cant use this.next() with a pattern like:

```
var authDispatcher = function (){
  let nextRt=Router.current().route.path();
  if (this.ready()) {
        if (!Meteor.user()){
          this.redirect('/authenticate'+nextRt);
        } else {
          this.render();
        }
  }
};

Router.route('/creditCard', {
  template: 'dialogHome',
  waitOn: waitOnSub,
  data: {dialogTemplate: 'register'},
  before: authDispatcher
});
```

i even tried doing a bind
  var thisNext = this.next.bind({});
no dice. 

The only solution i found to even get basic dispatching versus sub data to work in iron router is to put the entire logic inside the individual route definition like you've done in your  
second example above. IMHO It would be great if the maintainers of iron router reworked some of the examples and documentation to help people get the proper pattern down to handle conditional routing because it is certainly confusing as it stands now.

**Comment by chrisbutler** [comment]
@steveinatorx i think your issue is a little different than the original poster's

i think the solution for both of you  is [plugins](http://iron-meteor.github.io/iron-router/#plugins) ([this link](http://www.manuel-schoebel.com/blog/meteorjs-iron-router-filters-before-and-after-hooks) will also be helpful)

**Comment by chrisbutler** [comment]
also, [controllers](http://iron-meteor.github.io/iron-router/#route-controllers) are a useful way to re-use this kind of logic

**Comment by chrisbutler** [comment]
also, [controllers](http://iron-meteor.github.io/iron-router/#route-controllers) are a useful way to re-use this kind of logic

by the way @steveinatorx , i don't see what is wrong with your example.... (other than the hook is ```onBeforeAction``` but i'm assuming that's a typo)
