### ISSUE TITLE
Getting Template.onCreated to re-run

### ISSUE THREAD

**Issue by SachaG** [iron-meteor/iron-router#1337]
I'm using the `Template.onCreated` callback to initialize a bunch of template reactive variables for [template-level subscriptions](https://www.discovermeteor.com/blog/template-level-subscriptions/). 

The issue I'm running into is that if you change routes while still using the same template, IR doesn't re-run the `onCreated` callback. 

So for example, if I have a `/top` route to show popular posts, and a /`new` route that shows the most recent ones, since they're both using the same `posts_list` template, that template's `onCreated` won't rerun when switching routes and the subscription won't get properly reinitialized. 

What would be the best way around that? Is there a way to force the template to re-render when switching routes?

**Comment by cmather** [comment]
Create a reactive dependency on the route change.

current = Router.current()

Not tearing down the templates and creating them again is to avoid flicker on route changes.

**Comment by SachaG** [comment]
That makes sense. Actually maybe I need to find a different approach, where the route changes in parallel to the reactive variable, but isn't actually driving it. It does feel a bit wasteful to tear down the template unnecessarily.

**Comment by copleykj** [comment]
I'm not sure if it would help in your particular situation @SachaG, but I had this same issue and ended up moving the state off the template and onto the route controller using `Iron.controller().state` in my onCreated

**Comment by rclai** [comment]
@SachaG I'm not sure if you understood @cmather but I believe he's saying that the reason your onCreated doesn't rerun is because your template doesn't get destroyed because your routes were using the same template. If you want your subscription to rerun, you have to wrap your subscription inside an autorun and use Router.current().

**Comment by SachaG** [comment]
I've worked around my issue by putting my subscription code inside a template helper instead of the `onCreated` callback. 

Since template helpers get re-run when the template's data context change, it works for my purposes even though the template itself is not getting re-rendered.

**Comment by erasaur** [comment]
A little late to the party, but I also faced a similar issue a few days ago. I ended up using a method similar to @rclai's suggestion, and I thought I'd post an example [here](https://github.com/erasaur/binary/blob/devel/client/views/topics/topic.js) for anybody who'd like to see one. 

With all due respect to Sacha, I think the autorun offers a cleaner solution than helpers (at least in my case), since you won't have to include a dummy helper to trigger the subscriptions. Also, the data context could potentially change without there being an accompanying route change, so there might be some unexpected behavior with helpers. Just my 2c :-)

**Comment by rclai** [comment]
To summarize:

Any template's created (onCreated) or rendered (onRendered) hook will re-render only if the template was destroyed prior. Iron Router will not destroy your template if you navigate to a different route with the same template. So if you want to do reactive things on the same template if the route changes, you do:

```js
Template.yourTemplate.onCreated(function () {
  this.autorun(function () {
    if (Router.current().params.myParam) {
      // Do my stuff
    }
  });
});
```

**Comment by dcsan** [comment]
thanks for the top @rclai !

By using `this.autorun` that pattern is to make sure the autorun will be created together wtih the template, but what about destroyed/stopped? 
onCreated creates the autorun, but I'm not sure if the JS scoping whether Meteor tracks that internally, if it just gets added to some big list somewhere of things that keep autorunning until destroyed, or whether it will automatically get stopped when you leave the route.

**Comment by erasaur** [comment]
@dcsan the autorun should get destroyed with the template, Meteor is cool like that :)

**Comment by rclai** [comment]
If you do `this.autorun` inside an `onCreated` or `onRendered` they will get cleaned up automatically when they get destroyed (`this.subscribe`s inside them will also get stopped to)... and.. looks like @dcsan beat me to it.

**Comment by SachaG** [comment]
@erasaur you're right, I ended up bringing it back into the `onCreated`. @tmeasday reminded me you could use `Template.currentData()` to add a reactive dependency on the data context.

Here's the final code if you're interested: https://gist.github.com/SachaG/0bc20210c3e2c1e81600
