### ISSUE TITLE
Default Iron Router displays on first time using Android Cordova App

### ISSUE THREAD

**Issue by fredgreer** [iron-meteor/iron-router#1386]
Having a strange issue where my application works perfectly as a web app, but when deployed to Android, the first time I open the app I get the default iron router splash page for when no routes are defined. Closing and opening the app again fixes the problem.

The login page is displayed fine when deployed to iOS but logging in with facebook doesn't work until the app is relaunched. I get a facebook error saying the callback URL is on the wrong domain.

I suspect it may be related to this issue: https://github.com/iron-meteor/iron-router/issues/1152

Here are my related routes:

    Router.route('/', {
	name: 'home',
	where: 'client',
	controller: 'HomeController'
    });

and my before action:

    Router.onBeforeAction(function() {
	if (Meteor.userId()) {

		this.subscribe('loggedInUser', Meteor.userId()).wait();

		// force user to set a username if they haven't already
		if (!Meteor.user().profile.username) {
			this.layout('NoSidebarsLayout');
			this.render('ChooseUsername');
		} else {
			this.next();
		}
	} else {
		this.layout('NoSidebarsNoNavLayout');
		this.render('Login');
	}
    });

**Comment by fredgreer** [comment]
Hmm, this issue turned out to be having the MDG reload-on-resume package installed. Removing this fixed the issue.

**Comment by not-ai-yet** [comment]
I am still having this issue. Any other packages that may do this?

**Comment by PeppeL-G** [comment]
I'm facing this problem as well (except that closing the app doesn't solve the problem). Given the suggested solution, I tried to remove the package `reload` (I don't have the package `mdg:reload-on-resume` installed), but without any success.

Do Iron Router require a connection to the meteor server in order to work? Because I'm not connecting it to a server running Meteor (I use a dummy value as the server address in the build process).

**Comment by PeppeL-G** [comment]
For offline apps, I've found this statement:

> With iron router its a bit tricky but you can't use / you'll have to use index.html and relative paths

http://stackoverflow.com/a/27794917/2104665

I've tried to use relative paths, but failed, and I'm not sure how to do this. What is the relative path to `/`?

@cmather can you provide some guidance?

**Comment by PeppeL-G** [comment]
Oh, this is great. After some ~20 different builds I've come to the conclusion that something is wrong with the build process for production. My guess is that the minified JavaScript code somehow is wrong. My observed problem with Iron Router is not the only problem, I can't even get ordinary `alert` calls to work, which suggest that the execution of JavaScript code above the line of code with the `alert` call somehow has failed (which potentially could come from the `iron:router` package ;)). The best is that I can't debug this any further, because I need to build the project for production in order for the error to occur, but  Chrome/Android/WebView can only be (easily) debugged in debug builds...

Anyway, (this might interest you, @TheRealNate), building the project with the `--debug` flag and then using the `debug.apk` file is what I'm using for now.

**Comment by not-ai-yet** [comment]
@PeppeL-G Yup, that works for me, but I want to be able to publish it to Google Play (and it doesn't allow you to publish debug apks). Anybody know how to somehow remove whatever makes Google Play see it as debuggable?

**Comment by PeppeL-G** [comment]
@TheRealNate, perhaps you can use the same procedure as the guy at the link below used:

http://www.x-services.nl/sign-an-android-debug-apk-for-release-in-play/706
