### ISSUE TITLE
Support IE<10

### ISSUE THREAD

**Issue by cmather** [iron-meteor/iron-router#14]
This includes support for browsers that don't support pushState (i.e. IE<10).

It includes researching whether we should roll our own solution or use a library like history.js. The integration point would be with our Location class location in lib/client/location.js

Ideally, the user shouldn't need to think about this at all, other than possibly providing configuration options to the router. Asking the user to include additional packages to make this work shouldn't be required in my opinion. However, if/when Meteor implements conditional file loading for packages (e.g. based on user-agent) we could dynamically send down the right javascript.

**Comment by suprsidr** [comment]
I see this thread is old, but I ran into this last night. I don't care about IE8, but support for IE9 is still important to our company. Though IE<10 is only responsible for ~3% of total site traffic/mo that is ~$50,000 in revenue. I have seen many responses with partial fixes, and even some claiming this was fixed in v0.6. But I'm on iron:router@1.0.7 and most pages of my app are blank and all urls have hash bangs in them. @cmather is there some direction you can point me in?
Errors:
 Exception in setTimeout callback:Error: Syntax error, unrecognized expression: #!story/qZjvd5bRpHcn9EvKo 
 Exception from Tracker recompute function: 
 undefined 
 Exception in setTimeout callback:Error: Syntax error, unrecognized expression: #!search

**Comment by suprsidr** [comment]
So I thought I'd try a simple old polyfill https://cdn.polyfill.io/v1/docs/
And it works.
Please disregard my previous plea.
