### ISSUE TITLE
route to same route name doesn't reload the content

### ISSUE THREAD

**Issue by chongwang87** [iron-meteor/iron-router#1460]
i defined a route as per below

````javascript
Router.route('/company/:companySlug/showcase/:category', {
	name: 'company.showcase.category.index',
	template: 'company_showcase_index',
	controller: Company.controllers.default
});
````

when i in above route with `:category` for eg `productA` and route to the same route with different `:category` for eg `productB`, the template helpers, events, onCreated & onRendered contents doesn't reload. 

The page content still remain `productA`.

I tried to `console.log(this)` from `onCreated`, it does show `productA`, but when route to `productB` from the same route name, the console doesn't log.

working perfectly before update to Meteor 1.2.0.2 & iron:router 1.0.12

**Comment by sveinburne** [comment]
How did you define the reactive data source for this route?

**Comment by chongwang87** [comment]
this is my template javascript file

````javascript
Template['company_showcase_index'].helpers({
	products: function(){
		return Template.instance().products.get();
	},
	isReady: function(){
		return Template.instance().ready.get();
	}
})
Template['company_showcase_index'].onCreated(function(){
	var instance = this;
	instance.ready = new ReactiveVar(false);
	instance.products = new ReactiveVar([]);
	params = instance.data.params,
	company = instance.data.company;
	if ( params.category ){
		categories = company.showcase.categories;
		indexOfCategory = _.indexOf(categories, _.findWhere(categories, {slug : params.category}));
		brandIds = company.showcase.categories[indexOfCategory].brands;
		classificationsIds = company.showcase.categories[indexOfCategory].classifications;
	}
	instance.autorun(function(){
		var subscription = Meteor.subscribe('products', company._id);
		if (subscription.ready()){
			if ( params.category ){
				var products = Product.find({
					"company" : company._id,
					"$or" : [{
						"brands" : {
							'$in' : brandIds
						}
					},{
						"classifications" : {
							'$in' : classificationsIds
						}
					}]
				});
				instance.products.set(products);
			} else {
				var products = Product.find({
					"company" : company._id
				});
				instance.products.set(products);
			}
			instance.ready.set(true);
		} else {
			instance.ready.set(false);
		}
	})
})
````

**Comment by sveinburne** [comment]
Few comments about your code : 

- `Product.find(...)` returns a cursor, [which is a reactive data source](http://docs.meteor.com/#/full/find)! You don't need to have a `instance.products = new ReactiveVar([])`, just assign `instance.products=Products.find(...)`

- Since `Product.find()` is a cursor, you'll need to [fetch it](http://docs.meteor.com/#/full/fetch) instead of getting it. Replace 

```javascript
products: function(){
        return Template.instance().products.get();
    }
```
with 
```javascript 
products: function(){
        return Template.instance().products.fetch();
    },
```

Perhaps you could show me server-side `Meteor.publish('products')` for more insights. My feeling is that you should use [a callback as last argument of `subscribe` method ](http://docs.meteor.com/#/full/meteor_subscribe) to run your code when subscription is ready. Hope this helps!
