### ISSUE TITLE
Iron-router behind nginx proxy

### ISSUE THREAD

**Issue by kimmoahokas** [iron-meteor/iron-router#154]
It seems that iron router doesn't handle meteor environment variable ROOT_URL properly.

For example i  have defined route:

``` javascript
this.route('my_appointments', {
        path: '/',
        template: 'appointmentListTemplate',
    });
```

which works when running local debug server. In production environment I have to run meteor behind nginx reverse proxy, which has configuration like this:

```
server {
    listen [::]:80;
    server_name server.example.com;
    location /scheduler/ {
        proxy_pass http://localhost:3000;
        proxy_set_header  X-Real-IP  $remote_addr;
        proxy_set_header Host $host;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
    }
}
```

now I run the meteor server: `ROOT_URL="http://server.example.com/scheduler" PORT=3000 node main.js`
When i try to connect to http://server.example.com/scheduler I get this error to browser js console: "Error: No route found for path: /scheduler/".

Ok, so I figure out that I just modify the urls in router to something like this:

``` javascript
this.route('my_appointments', {
        path: '/scheduler',
        template: 'appointmentListTemplate',
    });
```

Now the index page at http://server.example.com/scheduler works but all the links produced by router contains additional scheduler part like this: http://server.example.com/scheduler/scheduler/reserve

Am I doing something wrong, or is this a bug in iron router?

**Comment by jasonshouse** [comment]
+1 for Iron Router to support ROOT_URL

**Comment by lllama** [comment]
This has just bitten me when trying to run the example todos app behind nginx and under a test URL (i.e. non-'/' location). Would be good if ROOT_URL could be supported. (pathFor caused the most obvious problem for me - links end up removing the initial path component)

**Comment by tlau** [comment]
+1 here too. We need to run multiple meteor apps within a single nginx instance, proxied from different subdomains (e.g. http://myhost/app1 and http://myhost/app2). It would be nice if we didn't have to rewrite the app to support being run in a subdomain.

**Comment by donpdonp** [comment]
+1. We have a simple meteor app with no routes and it works fine with a ROOT_URL of http://example.com/one. A more complex app is mounted at http://example.com/one.  The routes.js of path: '/' will fail because the ROOT_URL_PATH_PREFIX is not being removed and there is no route (nor should there be) for '/two/'

**Comment by baszalmstra** [comment]
+1. Would also like to run two meteor applications within the same single nginx instance.

**Comment by johdirr** [comment]
I've slightly modified the `URL.parse` function (https://github.com/johdirr/iron-url/commit/ff65e018c8d4a486bed64f5d593b434570f7850c) from the [iron:url](https://github.com/iron-meteor/iron-url) package to make all routes relative to the `ROOT_URL` env. Works for me..!

But I still have a problem with the IE9. For some reason meteor places the `/#/` (fallback for the missing History API) right **before** the `ROOT_URL_PATH_PREFIX`, which is wrong...

     http://example.com/one => http://example.com/#/one

I'm not sure if it has something to do with the Iron:Router because if I use the [`urlToHashStyle`](https://github.com/iron-meteor/iron-location/blob/master/lib/utils.js#L11) function everything looks fine and if I force Chrome or Firefox to use hash styled routes everything works fine too... any idea?
