### ISSUE TITLE
No Route Definitions Found

### ISSUE THREAD

**Issue by bakuur** [iron-meteor/iron-router#1582]
![whatsapp image 2017-05-17 at 9 07 16 am](https://cloud.githubusercontent.com/assets/15168353/26274557/24c438b2-3d01-11e7-916c-34efeb99f83d.jpeg)

I have compiled an .apk in production mode and released it to the app store,

I keep getting this error as soon as a I download it fresh from the app store, few moments later, it's gone and everything is fine.

This might work for me but it's not the way it should be.

I was at 1.1.2 and I tried downgrading the version used for the iron router to 1.1.1 and to 1.0.13 and nothing works.

Any idea on what I should do next?

**Comment by chrisbutler** [comment]
hi @bakuur, this is almost always because of an application bug... but they can be really tricky to track down

does running it locally in 'production mode' with ```meteor --production``` show any console errors or anything? if not, can you set up your logging in the production apk and try to figure out what's happening?

how large is your public folder and/or are you serving images or assets out of it?

also, you can try setting a ```noRoutesTemplate``` in a ```Router.configure({})``` block to a blank template and see if this screen still appears (https://github.com/iron-meteor/iron-router/blob/devel/Guide.md#global-default-options)

**Comment by bakuur** [comment]
Hi @chrisbutler ,
Thank you for your prompt response,
Turns out it was a build issue,

I was using the following command when building my apk
`meteor build ~/Release --settings settings.json --server http://my.web.site`

when using this fixed everything
`meteor build ~/Release --mobile-settings settings.json --server http://my.web.site`
