### ISSUE TITLE
Able users to save audio files for offline viewing

### ISSUE THREAD

**Issue by DDavis1025** [iron-meteor/iron-router#1603]
Okay so I'm creating a meteor app for ios and I want my users to be able to save html5 audio files for offline viewing. How do I proceed to do this?

**Comment by ddaydd** [comment]
Hi, lol, you want to "viewing???" listen 'pirated(sorry if is not :p)' music on ios, good luck, buy an android.

Otherwise an audio file, is a audio file.(wav, .mp3...), a html5 is a html file(.html) but a html5 audio file??
here is for issue, search to force download static file on stakoverflow... but in ios...

**Comment by DDavis1025** [comment]
I'm looking to be able to let my users make there own offline playlists to view offline like in Spotify using meteor
