### ISSUE TITLE
Cancel route

### ISSUE THREAD

**Issue by dalgard** [iron-meteor/iron-router#457]
I can't figure out how to prevent the browser from going to a route after, for instance, clicking a link to some place that I don't want the user to go to.

I've managed to implement calling up a login modal when triggering certain routes, but the address has already changed, so upon closing the modal, the user is actually located on a route that he or she does not have access to.

This must be a common problem?

**Comment by fusepilot** [comment]
@dalgard that is exactly what I'm trying to do right now. Did you have any luck with figuring it out? cc @cmather

**Comment by cmather** [comment]
Why don't you attach an event handler to any links that have a certain data identifier like `<a data-admin...`. You can cancel propagation of the event to tell iron router to ignore the click if the user isn't logged in. Otherwise just continue up the event chain as usual an IR will route. In your login screen, you could redirect to the admin page on successful login. So something like this:

```javascript
MyTemplate.events({
  'click [data-admin]': function (e, tmpl) {
    if (!Meteor.user()) {
      e.stopPropogation(); // check the method name
      Session.set('showLoginDialog', true);
    }
  }
});
```

**Comment by fusepilot** [comment]
Thanks for the quick response. 

The thought had crossed my mind. But since this is specifically a router/authentication problem, it feels like the responsiblity should be up to only the router and some authentication specific logic. Without having to alter or listen to the dom.

The onBeforeRouteChange functionallity proposed by https://github.com/iron-meteor/iron-router/issues/698 would help accomplish this I think.

````
Router.onBeforeRouteChange(function() {
  if(!Meteor.userId()) {
    showLoginModal(); //this would handle redirect on success
  } else {
    this.next();
  }
}, {only: ['admin', 'and', 'other', 'protected', 'pages']})
````
That feels cleaner to me than having to add modal specific events all over the project.

**Comment by dalgard** [comment]
I agree with the previous post.

**Comment by cmather** [comment]
Someone should take a stab at it and we can see how it feels. Probably involves a this.cancel method and adding some new state to the controller during dispatch.
