### ISSUE TITLE
Iron Router causes IOS chrome and dolphin browsers to crash

### ISSUE THREAD

**Issue by joarae** [iron-meteor/iron-router#498]
When viewing an Iron-Router configured meteor app using Google Chrome or Dolphin on iPhone, the browser quits unexpectedly.

Here is how you replicate the issue:

After opening up the meteor app in either chrome or dolphin, hit the Hold button of your iPhone (top right corner) and wait for a couple of minutes.

After waiting for a couple of minutes, unlock your phone and you should be able to see chrome as your active running application. Chrome or dolphin somehow crashes.
You may or may not be able to reproduce this the first time. But you should be able to experience this more often.

I have tried to remove all installed packages and everything seems to work well. But after I added back the iron-router package, chrome starts to display the crashing behavior again.

You can replicate this issue even with the most basic configuration. Even a static meteor app, no configured routes, no subscriptions involved, just plain installed IR.

Issue occur even with the latest version of IOS and chrome.

I tried making use of Safari, and it seems to work pretty well. 

Please let me know your thoughts?

Thanks

**Comment by sangyoo91** [comment]
I came across the same problem.

iOS Safari No problem.
iOS Chrome Yes Problem.

Back button works fine, but when I visit a page with params such as `/abc/:_id` and then go back, it won't work..

I am subscribing to the server with `Router.current().params._id`  in `Template.onCreated` if this helps .

EDIT :

For additional information, the back button DOES change the route, but the problem is that the page wont change accordingly one visited a route that has `params`.
