### ISSUE TITLE
Access to the raw request body needed

### ISSUE THREAD

**Issue by slawo** [iron-meteor/iron-router#534]
The raw data from a `request.body` is not available from the controller.

This makes it impossible to perform some tasks like: 
- testing data integrity and origin (md5 or sha1 digests)
- parsing non JSON data
- replacing raw text before `JSON.parse()`

**Comment by fongandrew** [comment]
@gerwinbrunner Did you ever figure this out?

**Comment by gerwinbrunner** [comment]
Nope, I found a different way to solve my problem. Sorry.

**Comment by isAlmogK** [comment]
Has anyone solved this

**Comment by cmather** [comment]
Whoa, it's been a little while but got an email notification so figured I'd try to help :-). I'm guessing the issue is that people want the request body and it's currently undefined? The request object in nodejs is a stream so this is a bit of a weird process. It's been a while since I looked at what middleware and other stuff is in the router. But dealing with the raw request object is simple enough. Let me see if I can cook up an example (give me a second).

**Comment by isAlmogK** [comment]
@chrisbutler it's all good I got it working using formidable more info here - http://stackoverflow.com/questions/36253438/sendgrid-inbound-webhook-sending-empty-body

**Comment by cmather** [comment]
**index.js**
```javascript
const http = require('http');

const server = http.createServer(function(req, res) {
  // create an array to store the chunks of data from the request stream.
  let chunks = []

  // we'll eventually create a single string with the entire body.
  let body;

  // notice the request (req) is a nodejs readable stream
  // (https://nodejs.org/api/stream.html). it's sort of like stdin. so we might
  // not get the entire body at once, but as chunks over some period of time. so
  // we'll listen for the 'data' event and push each chunk we get onto an array.
  req.on('data', function(chunk) {
    chunks.push(chunk.toString());
  });

  // when there's no more data from the request we'll set the body property to
  // the result of joining the chunks array, which creates a single concatenated
  // string. then we'll just echo back to the client whatever was in the body.
  req.on('end', function() {
    body = chunks.join();
    res.end(body + '\n');
  });
});

server.listen(3000);
console.log(`http server listening on http://localhost:3000`);
```

**usage**
```bash
> node index.js
```

**Comment by cmather** [comment]
An example of the same thing as connect middleware. The middleware does the req reading dance and sets the body property of the request. Note, this means the body will be completely read into memory. And I know this issue is for iron-router rather than raw connect. But the router uses the same api as connect if I recall from all those years ago :).

```javascript
const http = require('http');
const connect = require('connect');

function middleware(req, res, next) {
  // create an array to store the chunks of data from the request stream.
  let chunks = []
  let body;

  req.on('data', function (chunk) {
    chunks.push(chunk.toString());
  });

  req.on('end', function() {

    // notice we're putting the entire body content on the req object now, to be
    // used by downstream middlewares or the app.
    req.body = chunks.join();

    // ok now that we have the body, pass control to the next middleware.
    next();
  });
}

// create the connect middleware app
const app = connect();

// plug in the middleware
app.use(middleware);

app.use(function(req, res) {
  // just echo back the body to the response stream.
  res.end(req.body + '\n');
});

app.listen(3000);
console.log(`http server listening on http://localhost:3000`);
```

**Comment by chrisbutler** [comment]
awesome to see you back here @cmather! haha

**Comment by chrisbutler** [comment]
@AlmogRnD that's why i was asking for more info in the other thread... i figured there was something else in the mix and the multi-part form bit was it

glad you figured it out
