### ISSUE TITLE
Matching url with double slash

### ISSUE THREAD

**Issue by carlbrn** [iron-meteor/iron-router#565]
Hi, 
Is there a way to match an url with double slash in iron-router ?
Example : http://thewebsite.com//example/url

I tried things like that but it didn't work:

Router.map(function () {
    this.route("routeName", {
        path:"//_",   or  /%2F, /%, /%_, */%
    });
});

Thanks.

**Comment by Dsyko** [comment]
This seems to be an issue for server side routes as well, for some reason creating a route with a path which starts with two slashes does not match. For example `path:  "//user/login"` doesn't match http:www.example.com//user/login on the server side. Triple slashes seem to work fine for some reason. (as a side not on localhost the route matches but it doesn't in production)

I've also tried using a RegExp for the path instead of a string and it also doesn't match the double leading slash.
`path: new RegExp("^/*user/login$");`

This double slashed route path used to work in an older version of Iron Router before the 1.0 changes.

My current solution is to monkey patch the dispatch function to remove extra leading slashes on routes, but it doesn't feel right...
