### ISSUE TITLE
pathFor not working anymore with dynamic query parameters

### ISSUE THREAD

**Issue by hamal** [iron-meteor/iron-router#589]
Hi,
before the last update (0.7) I had something like this:

```
{{#each posts}}
    <a href="{{pathFor 'postsRoute' view=viewMethod}}">link</a>
{{/each}}
```

Where the object post has a field named viewMethod and the resulting url was similar to 

```
/posts/?view=image
```

Now this solution it's not working anymore. Any advice or suggestion? 

Thanks,

Francesco

**Comment by cyllu2** [comment]
Dear @cmather, fuck you.

**Comment by richardartoul** [comment]
@guillermosan I just ran into the same problem. I ended up using something that looks like this:

<a href="/listWorkouts/?userId={{_id}}"></a> where I manually spell out the url path instead of using path for. It seems like path for really loses alot of utility as a result of not being able to handle dynamic queries.

I'd happy to make a pull request to solve this issue, but I'm not quite sure where to start. Is this an iron router issue or a jade issue? Either way, I think this is definitely something that warrants improving.

**Comment by elpddev** [comment]
Using semi identity function helper, I have ended with something that gave that dynamic functionality back to `pathFor`. Thanks to @hamal snippet, I have registered it as global helper. 

```javascript  
Template.registerHelper('asHash', function (params) {
  return params.hash;
});
```

```html
a href="{{pathFor route='product' query=(asHash id=product.id zone=product.zone) }}">Product</a>
```
