### ISSUE TITLE
Error: Request Entity Too Large

### ISSUE THREAD

**Issue by laddi** [iron-meteor/iron-router#710]
We are trying to do some json parsing with a large file in a server route and run into this problem: "Error: Request Entity Too Large"

Instead of having to manually edit the package code it would be nice to have some kind of way to set the bodyParser limit in the configuration.

(same issue as here: http://stackoverflow.com/questions/23899209/setting-request-limit-in-a-meteor-js-app)

All help greatly appreciated.

**Comment by landland** [comment]
I'm running into this issue as well. Any chance we can up the limit in iron router?

**Comment by travisdahl** [comment]
+1. Trying to upload 3 images as base64 (i save to s3 on server) but limit wont allow

**Comment by cmather** [comment]
@gerwinbrunner has the right idea. But you can put this in Router.configureBodyParsers on the server. Look in lib/router_server.js for how it's done in source. Here's an example:

```javascript
Router.configureBodyParsers = function () {
  Router.onBeforeAction(Iron.Router.bodyParser.json({limit: '10mb'});
};
```

For uploading files, @DirkStevens can you show an example of how to do it? We worked on an example together. 

I haven't had time to properly integrate multipart uploading. Under the hood Iron Router just uses body parser for parsing http bodies. And at some point they decided not to support multipart uploads (I didn't realize this until last weekend). So we have to plug in a third party multipart uploading Connect middleware package, or you can do it yourself. There are a few npm packages for this (http://www.senchalabs.org/connect/multipart.html).

**Comment by DirkStevens** [comment]
Hey all - at https://github.com/EventedMind/iron-router/issues/1190 you'll find info and a link to an experimental "multipart" package that @cmather and I worked on.

**Comment by travisdahl** [comment]
@cmather , just as @gerwinbrunner mentioned...
>Just adding the line in my own code did not fix the error, so I had to fork and change the original.
But now it works. :)

adding this to my own server side code doesn't seem to make a difference. I still get the limit warning. Any ideas why defining it in our own code wouldn't work?

**Comment by kkm** [comment]
@travisdahl 
Can you tell me which version did you use for iron router.
I did try with 1.0.7.1 but doesnt work for me.

**Comment by kkm** [comment]
AH I found:
Router = new Iron.Router;
Router.configureBodyParsers = function() {
  Router.onBeforeAction(Iron.Router.bodyParser.urlencoded({
    extended : true,
    limit : '500mb'
  }));
};

I didnt know that it needs class of Iron.Router..that is fix now..thanks

**Comment by fipppi** [comment]
For people who still encounter this issue after adding the above snippet from @kkm (minus the not-needed `Router = new Iron.Router;` line), your problem may very well be the placement of the said snippet. 

Move your `Router.configureBodyParsers = function() ...` snippet to be **immediately before your route definitions**. I had placed the snippet in a Meteor.startup() block in the `server/main.js` file and this *did not work*. Moving the snippet to `lib/routes/main.js` (immediately before my routes) solved this issue! 

I believe this is because the `Router` object gets initialised after the code in `server/main.js`, meaning it overwrites the extended function. Hopefully this saves someone the months of trouble it caused me!
