### ISSUE TITLE
"Organize your Meteor application." splash page

### ISSUE THREAD

**Issue by dfischer** [iron-meteor/iron-router#996]
I'm getting a "Organize your Meteor application." splash page error for a site when deployed via meteor deploy but locally it renders fine. 

What would cause this?

**Comment by quickj** [comment]
@karayu I have the same issue with the iron router on the production mod. I'm getting a "Organize your Meteor application." splash page. I don't know how to fix it.I update the meteor before. Here is the project link https://github.com/ReneMoraales/songroll-sky . Can you help me,very thanks!

**Comment by v1nay** [comment]
fixed the same issue. check https://github.com/iron-meteor/iron-router/issues/1168#issuecomment-78245558

**Comment by Practice0** [comment]
In case this could help anyone get any ideas for debugging: (All of these problems occurred on my staging server not on localhost) At first I was getting a "No Route Definitions Found" error screen until I downgraded to iron:router 1.0.13. But then I started getting an "Organize your meteor application" error screen. I checked the console and found two errors: a "unreachable code after return statement" and a ReferenceError (Mongo is not defined).

I could not figure out if there was an error in the unique code (the unique code of an app written on top of meteor's platform). So, I decided to check out the source code. I copied the whole source into my text editor (if you're thinking of this, remember that it can be a lot so save anything you have open just in case) and then checked the line that the error was referencing and saw that it was related to a package I had downloaded called lookback:seo. 

I deleted it and the app worked. I'm not sure why though because I've had the package for quite some time and suddenly it started to call this error. 

Perhaps I updated something at one point, it caused incompatibilities and did not remember? - I don't know (if you figure out that lookback:seo is causing the problem for you as well and you'd prefer to keep the package, you can check this out: https://github.com/lookback/meteor-seo/pull/24 .). I recommend doing something like this if all else fails. 

Check out the source by copying the src attribute of the longest script tag and appending that to the url you're currently at (ex. example.com/{{src tag}}). Copy all of it and paste to some text editor (I used gedit) (it can be a lot so save anything you have open just in case) and find the position of the problem indicated in the browser console. Check out the package that's creating the line of code that's causing trouble and, if you can afford to, try removing that package.

I was only using lookback:seo to insert titles into my documents as they were loaded so instead I opted for a solution proposed by Thomas Hromnik (here: http://stackoverflow.com/questions/19882687/set-html-title-when-using-iron-router) where I simply did something like this: onAfterAction: function() {document.title = 'page title';}. So I hope this helps someone. Cheers!

**Comment by chrisbutler** [comment]
@Practice0 thanks for posting this!

when people see this page, it's literally almost always a unique code bug... and almost always visible in the console (sometimes you need to run it locally in 'production mode' ```meteor --production``` to see/debug)

**Comment by lulutru** [comment]
Hi everybody,

We are having the same issue only  in Internet Eplorer and totally random... We have reviewed the console (js console) and running app in production mode and there's nothing in consoles.

This is what we get:
    ```
iron:router Organize your Meteor application.
    Router.route('/', function () {
      this.render('Home', {
        data: function () { return Items.findOne({_id: this.params._id}) }
      });
    });

```
This is the code we have in router.js for Home:
    ```
Router.route('/',{
      name: 'home',
      layoutTemplate: 'homeLayout',
      title: 'Log in',
      onBeforeAction: function(){
        this.redirect('/sign-in');
        this.next();
      }
    })
```

Versions we are using:
iron:router@1.0.13
MeteorJs: 1.3.5

Thanks in advance for your help!

**Comment by chrisbutler** [comment]
@lulutru which version of IE? just to re-iterate the above... this really is not a problem with IronRouter, it's likely some other package...

**Comment by lulutru** [comment]
Hi @chrisbutler !
Thanks for your response, 
We get this error with IE 9 and older. Now, the app works if updates the page.

Thanks in advance!

**Comment by chrisbutler** [comment]
@lulutru sorry but we don't support IE9, and most packages will break on it i think

**Comment by lulutru** [comment]
OK! Thanks anyway @chrisbutler ! If we find some solution I'll write here.

**Comment by chrisbutler** [comment]
@lulutru does it work when you have the developer tools open? do you have `console.log` statements in your app?

**Comment by lulutru** [comment]
Hi again @chrisbutler, until today there was nothing in console.
Today we have these errors:
SCRIPT5022: Router.route requires a path that is a string or regular expression.
SCRIPT5007: Unable to get value of the property  'length':: object is null or undefined  

We are going to search if they are the problem!

Thanks  for your answers!
